
# version format
version: 3.0.17.{build}

# environment
environment:
  majorversion: 3
  minorversion: 0
  patchversion: 17

image: Visual Studio 2017


# Do not build on tags
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: nuget restore src/UIOMatic.sln

build_script:
  - msbuild build/package.proj 
  
artifacts:
  - path: artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: cRKDqHqagUzMgXLZ971fBXwpacf44O7jsIk7hfeLNo75kShTMknWjQfWLGxgKIPt
  artifact: /.*\.nupkg/
